# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "uat" , "development" ]
    tags: [ "^u*" , "^v*" ]
    
#  This is Environment 1

# env:
#   file_name: env1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
       inside: inside@build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: build
        run: docker build -t a8017/webapp:latest -t a8017/webapp:$GITHUB_REF_NAME -f Dockerfile .

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: push
        run: | 
          docker push a8017/webapp:latest
          docker push a8017/webapp:$GITHUB_REF_NAME

      


      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: | 
      #    echo Hello, world! $file_name
      #    echo $inside
      #    echo $outside

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo hello , world! $file_name
      #     echo $inside
      #     echo $outside
          

      #   env:
      #      outside: inside_step
